name: Build and Deploy React App via Docker
################################################################################
# This action will build and push a Docker image to Docker Hub and deploy it to
# a VPS. It will also set up an OpenVPN connection to the VPS.
#
#  -------------------------- /!\ Important Notes /!\ --------------------------
# 
# - The Docker container will be named based on the format:
#   `${{ github.repository_owner }}-${{ github.event.repository.name }}-container`.
# - There is an Apache2 VHost behind the VPS's associated domains that will
#   reverse proxy to the Docker container.
# - There is also a systemd service that will restart the Docker container if 
#   it crashes.
#
# So any update on application ports must be reflected in the VHost and
# systemd service configuration files.
#  --------------------------- /!\ Required Creds /!\ --------------------------
# 
# - DOCKER_USERNAME: Docker Hub username
# - DOCKER_PASSWORD: Docker Hub password
# - OPENVPN_USERNAME: OpenVPN username
# - OPENVPN_PASSWORD: OpenVPN password
# - SSH_USER_DEV: SSH username
# - SSH_PASSWORD_DEV: SSH password
# - SSH_PORT_DEV: SSH port
# - SSH_IP_ADDR_DEV: SSH IP address
# - ENV_FILE_DEV: Content of the .env file
#
################################################################################

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate Docker credentials
        run: |
          [ -n "${{ secrets.DOCKER_USERNAME }}" ] || { echo "Missing DOCKER_USERNAME"; exit 1; }
          [ -n "${{ secrets.DOCKER_PASSWORD }}" ] || { echo "Missing DOCKER_PASSWORD"; exit 1; }

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare Docker metadata
        run: |
          echo "DOCKER_IMAGE=$(echo '${{ secrets.DOCKER_USERNAME }}/lelicorne-server-states-dashboard-preprod' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ github.ref_name }}
